services:
  mysql:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: develop
    ports:
      - 3306:3306
    volumes:
        - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local

